export enum ColorsEnum {
  background = '--wo_background',
  background_additional = '--wo_background_additional',
  background_warning = '--wo_background_warning',
  text_high_emphasis = '--wo_text_high_emphasis',
  text_mid_emphasis = '--wo_text_mid_emphasis',
  text_low_emphasis = '--wo_text_low_emphasis',
  text_field_underline = '--wo_text_field_underline',
  separator = '--wo_separator',
  text_field_surface = '--wo_text_field_surface',
  snackbar = '--wo_snackbar',
  primary = '--wo_primary',
  primary_variant = '--wo_primary_variant',
  secondary = '--wo_secondary',
  secondary_variant = '--wo_secondary_variant',
  error = '--wo_error',
  skeleton1 = '--wo_skeleton1',
  skeleton2 = '--wo_skeleton2',
  text_primary_surface = '--wo_text_primary_surface',
  card = '--wo_card',
  card_high_emphasis = '--wo_card_high_emphasis',
  card_mid_emphasis = '--wo_card_mid_emphasis',
  primary_opacity_10 = '--wo_primary_opacity_10',
  menu_item_bg = '--wo_menu_item_bg',
  text_on_error = '--wo_text_on_error',
  box_shadow = '--wo_box_shadow',
}
