export enum TypographyEnum {
  'txt-h1' = 'txt-h1',
  'txt-h2' = 'txt-h2',
  'txt-h3' = 'txt-h3',
  'txt-h4' = 'txt-h4',
  'txt-h5' = 'txt-h5',
  'txt-h6' = 'txt-h6',
  'txt-subtitle1' = 'txt-subtitle1',
  'txt-subtitle2' = 'txt-subtitle2',
  'txt-body1' = 'txt-body1',
  'txt-body2' = 'txt-body2',
  'txt-button' = 'txt-button',
  'txt-caption' = 'txt-caption',
  'txt-overline' = 'txt-overline',
}
